name: Deploy to Netlify

on: 
    workflow_dispatch:
      inputs:
        release_tag:
          type: string
          required: true
          description: Release tag

run-name: Deploy ${{ inputs.release_tag }} to Production

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with: 
          ref: ${{ inputs.release_tag }}

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Netlify
        run: npm install netlify-cli@17.37.2 -g

      - name: Install Dependencies
        run: yarn

      - name: Sanitize
        run: yarn sanitize:check 

      - name: Build
        run: npm run build

      - name: Deploy to Netlify
        run: |
          netlify deploy --dir dist --site ${{ secrets.NETLIFY_SITE_ID }} --auth ${{ secrets.NETLIFY_API_TOKEN }} > deploy_output.txt
          echo "NETLIFY_PREVIEW_URL=$(cat deploy_output.txt | grep 'Website draft URL: ' | cut -d' ' -f4)"
